/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as EnumerableNFTContractJson } from "../nft/EnumerableNFT.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace EnumerableNFTTypes {
  export type Fields = {
    collectionId: HexString;
    tokenUri: HexString;
    nftIndex: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNFTIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  EnumerableNFTInstance,
  EnumerableNFTTypes.Fields
> {
  at(address: string): EnumerableNFTInstance {
    return new EnumerableNFTInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParams<EnumerableNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenUri", params);
    },
    getCollectionId: async (
      params: Omit<
        TestContractParams<EnumerableNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getCollectionId", params);
    },
    getNFTIndex: async (
      params: Omit<
        TestContractParams<EnumerableNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getNFTIndex", params);
    },
  };
}

// Use this object to test and deploy the contract
export const EnumerableNFT = new Factory(
  Contract.fromJson(
    EnumerableNFTContractJson,
    "",
    "299d7f939788bf812205d8776b49e6bc393574848cc173c92bb7798ebc518925"
  )
);

// Use this class to interact with the blockchain
export class EnumerableNFTInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<EnumerableNFTTypes.State> {
    return fetchContractState(EnumerableNFT, this);
  }

  methods = {
    getTokenUri: async (
      params?: EnumerableNFTTypes.CallMethodParams<"getTokenUri">
    ): Promise<EnumerableNFTTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        EnumerableNFT,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionId: async (
      params?: EnumerableNFTTypes.CallMethodParams<"getCollectionId">
    ): Promise<EnumerableNFTTypes.CallMethodResult<"getCollectionId">> => {
      return callMethod(
        EnumerableNFT,
        this,
        "getCollectionId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params?: EnumerableNFTTypes.CallMethodParams<"getNFTIndex">
    ): Promise<EnumerableNFTTypes.CallMethodResult<"getNFTIndex">> => {
      return callMethod(
        EnumerableNFT,
        this,
        "getNFTIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends EnumerableNFTTypes.MultiCallParams>(
    calls: Calls
  ): Promise<EnumerableNFTTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      EnumerableNFT,
      this,
      calls,
      getContractByCodeHash
    )) as EnumerableNFTTypes.MultiCallResults<Calls>;
  }
}
