/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NFTCollectionBaseContractJson } from "../nft_collection_base.ral.json";

// Custom types for the contract
export namespace NFTCollectionBaseTypes {
  export type Fields = {
    name: HexString;
    symbol: HexString;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintedEvent = ContractEvent<{
    minter: HexString;
    tokenIndex: bigint;
    tokenId: HexString;
  }>;
}

class Factory extends ContractFactory<
  NFTCollectionBaseInstance,
  NFTCollectionBaseTypes.Fields
> {
  at(address: string): NFTCollectionBaseInstance {
    return new NFTCollectionBaseInstance(address);
  }

  async testGetNameMethod(
    params: Omit<
      TestContractParams<NFTCollectionBaseTypes.Fields, never>,
      "testArgs"
    >
  ): Promise<TestContractResult<HexString>> {
    return testMethod(this, "getName", params);
  }

  async testGetSymbolMethod(
    params: Omit<
      TestContractParams<NFTCollectionBaseTypes.Fields, never>,
      "testArgs"
    >
  ): Promise<TestContractResult<HexString>> {
    return testMethod(this, "getSymbol", params);
  }

  async testTotalSupplyMethod(
    params: Omit<
      TestContractParams<NFTCollectionBaseTypes.Fields, never>,
      "testArgs"
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "totalSupply", params);
  }

  async testNftByIndexMethod(
    params: TestContractParams<NFTCollectionBaseTypes.Fields, { index: bigint }>
  ): Promise<TestContractResult<[HexString, boolean]>> {
    return testMethod(this, "nftByIndex", params);
  }
}

// Use this object to test and deploy the contract
export const NFTCollectionBase = new Factory(
  Contract.fromJson(
    NFTCollectionBaseContractJson,
    "",
    "dc896f852f44196e5615609c00b3a70ca064c4ce7f0e5e5f258f1dd51cf3bb25"
  )
);

// Use this class to interact with the blockchain
export class NFTCollectionBaseInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTCollectionBaseTypes.State> {
    return fetchContractState(NFTCollectionBase, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintedEvent(
    options: SubscribeOptions<NFTCollectionBaseTypes.MintedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTCollectionBase.contract,
      this,
      options,
      "Minted",
      fromCount
    );
  }

  async callGetNameMethod(
    params?: Omit<CallContractParams<{}>, "args">
  ): Promise<CallContractResult<HexString>> {
    return callMethod(
      NFTCollectionBase,
      this,
      "getName",
      params === undefined ? {} : params
    );
  }

  async callGetSymbolMethod(
    params?: Omit<CallContractParams<{}>, "args">
  ): Promise<CallContractResult<HexString>> {
    return callMethod(
      NFTCollectionBase,
      this,
      "getSymbol",
      params === undefined ? {} : params
    );
  }

  async callTotalSupplyMethod(
    params?: Omit<CallContractParams<{}>, "args">
  ): Promise<CallContractResult<bigint>> {
    return callMethod(
      NFTCollectionBase,
      this,
      "totalSupply",
      params === undefined ? {} : params
    );
  }

  async callNftByIndexMethod(
    params: CallContractParams<{ index: bigint }>
  ): Promise<CallContractResult<[HexString, boolean]>> {
    return callMethod(NFTCollectionBase, this, "nftByIndex", params);
  }
}
