/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as NFTPublicSaleCollectionRandomWithRoyaltyContractJson } from "../nft/publicsale/random/NFTPublicSaleCollectionRandomWithRoyalty.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace NFTPublicSaleCollectionRandomWithRoyaltyTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    collectionOwner: Address;
    nftBaseUri: HexString;
    maxSupply: bigint;
    mintPrice: bigint;
    royaltyRate: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{ minter: Address; index: bigint }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    royaltyAmount: {
      params: CallContractParams<{ tokenId: HexString; salePrice: bigint }>;
      result: CallContractResult<bigint>;
    };
    payRoyalty: {
      params: CallContractParams<{ payer: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawRoyalty: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getCollectionOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getMaxSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    withdraw: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNFTUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    royaltyAmount: {
      params: SignExecuteContractMethodParams<{
        tokenId: HexString;
        salePrice: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    payRoyalty: {
      params: SignExecuteContractMethodParams<{
        payer: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawRoyalty: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getCollectionOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMaxSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNFTUri: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getMintPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  NFTPublicSaleCollectionRandomWithRoyaltyInstance,
  NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields
> {
  encodeFields(fields: NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Mint: 0 };
  consts = {
    PublicSaleErrorCodes: { IncorrectTokenIndex: BigInt("0") },
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("2"),
      NFTNotFound: BigInt("0"),
      CollectionOwnerAllowedOnly: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): NFTPublicSaleCollectionRandomWithRoyaltyInstance {
    return new NFTPublicSaleCollectionRandomWithRoyaltyInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    royaltyAmount: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { tokenId: HexString; salePrice: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "royaltyAmount", params, getContractByCodeHash);
    },
    payRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { payer: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "payRoyalty", params, getContractByCodeHash);
    },
    withdrawRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawRoyalty", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    getCollectionOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(
        this,
        "getCollectionOwner",
        params,
        getContractByCodeHash
      );
    },
    getMaxSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMaxSupply", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    getNFTUri: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getNFTUri", params, getContractByCodeHash);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMintPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const NFTPublicSaleCollectionRandomWithRoyalty = new Factory(
  Contract.fromJson(
    NFTPublicSaleCollectionRandomWithRoyaltyContractJson,
    "",
    "d723a046f7e3171257508a14b831c0a54bad8ab9cf3c5959775dc0736c9dec28",
    []
  )
);
registerContract(NFTPublicSaleCollectionRandomWithRoyalty);

// Use this class to interact with the blockchain
export class NFTPublicSaleCollectionRandomWithRoyaltyInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPublicSaleCollectionRandomWithRoyaltyTypes.State> {
    return fetchContractState(NFTPublicSaleCollectionRandomWithRoyalty, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<NFTPublicSaleCollectionRandomWithRoyaltyTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTPublicSaleCollectionRandomWithRoyalty.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"validateNFT">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    royaltyAmount: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"royaltyAmount">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"royaltyAmount">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "royaltyAmount",
        params,
        getContractByCodeHash
      );
    },
    payRoyalty: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"payRoyalty">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"payRoyalty">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "payRoyalty",
        params,
        getContractByCodeHash
      );
    },
    withdrawRoyalty: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"withdrawRoyalty">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"withdrawRoyalty">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "withdrawRoyalty",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"mint">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    getCollectionOwner: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getCollectionOwner">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getCollectionOwner">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMaxSupply: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getMaxSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getMaxSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMaxSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"withdraw">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getNFTUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getNFTUri",
        params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "validateNFT",
        params
      );
    },
    royaltyAmount: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"royaltyAmount">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"royaltyAmount">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "royaltyAmount",
        params
      );
    },
    payRoyalty: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"payRoyalty">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"payRoyalty">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "payRoyalty",
        params
      );
    },
    withdrawRoyalty: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"withdrawRoyalty">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"withdrawRoyalty">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "withdrawRoyalty",
        params
      );
    },
    mint: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"mint">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "mint",
        params
      );
    },
    getCollectionOwner: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"getCollectionOwner">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"getCollectionOwner">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionOwner",
        params
      );
    },
    getMaxSupply: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"getMaxSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"getMaxSupply">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMaxSupply",
        params
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"withdraw">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "withdraw",
        params
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"getNFTUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getNFTUri",
        params
      );
    },
    getMintPrice: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.SignExecuteMethodResult<"getMintPrice">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMintPrice",
        params
      );
    },
  };

  async multicall<
    Calls extends NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<
    NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallResults<Calls>
  >;
  async multicall<
    Callss extends NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallParams[]
  >(
    callss: Narrow<Callss>
  ): Promise<
    NFTPublicSaleCollectionRandomWithRoyaltyTypes.MulticallReturnType<Callss>
  >;
  async multicall<
    Callss extends
      | NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallParams
      | NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      NFTPublicSaleCollectionRandomWithRoyalty,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
