/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as NFTPublicSaleCollectionSequentialWithRoyaltyContractJson } from "../nft/publicsale/sequential/NFTPublicSaleCollectionSequentialWithRoyalty.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace NFTPublicSaleCollectionSequentialWithRoyaltyTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    nftBaseUri: HexString;
    collectionOwner: Address;
    maxSupply: bigint;
    mintPrice: bigint;
    maxBatchMintSize: bigint;
    royaltyRate: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    minter: Address;
    fromIndex: bigint;
    mintSize: bigint;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    royaltyAmount: {
      params: CallContractParams<{ tokenId: HexString; salePrice: bigint }>;
      result: CallContractResult<bigint>;
    };
    payRoyalty: {
      params: CallContractParams<{ payer: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawRoyalty: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    mint_: {
      params: CallContractParams<{ minter: Address; index: bigint }>;
      result: CallContractResult<HexString>;
    };
    mint: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    mintBatch: {
      params: CallContractParams<{ size: bigint }>;
      result: CallContractResult<HexString>;
    };
    withdraw: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNFTUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    royaltyAmount: {
      params: SignExecuteContractMethodParams<{
        tokenId: HexString;
        salePrice: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    payRoyalty: {
      params: SignExecuteContractMethodParams<{
        payer: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawRoyalty: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    mint_: {
      params: SignExecuteContractMethodParams<{
        minter: Address;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    mintBatch: {
      params: SignExecuteContractMethodParams<{ size: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNFTUri: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getMintPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  NFTPublicSaleCollectionSequentialWithRoyaltyInstance,
  NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields
> {
  encodeFields(
    fields: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields
  ) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Mint: 0 };
  consts = {
    PublicSaleErrorCodes: { IncorrectTokenIndex: BigInt("0") },
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("2"),
      InvalidMintBatchSize: BigInt("3"),
      InsufficientNumOfUnminted: BigInt("4"),
      NFTNotFound: BigInt("0"),
      CollectionOwnerAllowedOnly: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): NFTPublicSaleCollectionSequentialWithRoyaltyInstance {
    return new NFTPublicSaleCollectionSequentialWithRoyaltyInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    royaltyAmount: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { tokenId: HexString; salePrice: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "royaltyAmount", params, getContractByCodeHash);
    },
    payRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { payer: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "payRoyalty", params, getContractByCodeHash);
    },
    withdrawRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawRoyalty", params, getContractByCodeHash);
    },
    mint_: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { minter: Address; index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint_", params, getContractByCodeHash);
    },
    mint: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    mintBatch: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { size: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mintBatch", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    getNFTUri: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getNFTUri", params, getContractByCodeHash);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMintPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const NFTPublicSaleCollectionSequentialWithRoyalty = new Factory(
  Contract.fromJson(
    NFTPublicSaleCollectionSequentialWithRoyaltyContractJson,
    "",
    "4cdc890635635f64a7697b2e73a35fa5a0faf74ebfe2fb8bdea16d4e24302b88",
    []
  )
);
registerContract(NFTPublicSaleCollectionSequentialWithRoyalty);

// Use this class to interact with the blockchain
export class NFTPublicSaleCollectionSequentialWithRoyaltyInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPublicSaleCollectionSequentialWithRoyaltyTypes.State> {
    return fetchContractState(
      NFTPublicSaleCollectionSequentialWithRoyalty,
      this
    );
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTPublicSaleCollectionSequentialWithRoyalty.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"validateNFT">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    royaltyAmount: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"royaltyAmount">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"royaltyAmount">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "royaltyAmount",
        params,
        getContractByCodeHash
      );
    },
    payRoyalty: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"payRoyalty">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"payRoyalty">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "payRoyalty",
        params,
        getContractByCodeHash
      );
    },
    withdrawRoyalty: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"withdrawRoyalty">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"withdrawRoyalty">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "withdrawRoyalty",
        params,
        getContractByCodeHash
      );
    },
    mint_: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"mint_">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"mint_">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mint_",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params?: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"mint">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mint",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    mintBatch: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"mintBatch">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"mintBatch">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mintBatch",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"withdraw">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"getNFTUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getNFTUri",
        params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "validateNFT",
        params
      );
    },
    royaltyAmount: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"royaltyAmount">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"royaltyAmount">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "royaltyAmount",
        params
      );
    },
    payRoyalty: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"payRoyalty">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"payRoyalty">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "payRoyalty",
        params
      );
    },
    withdrawRoyalty: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"withdrawRoyalty">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"withdrawRoyalty">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "withdrawRoyalty",
        params
      );
    },
    mint_: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"mint_">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"mint_">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mint_",
        params
      );
    },
    mint: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"mint">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mint",
        params
      );
    },
    mintBatch: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"mintBatch">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"mintBatch">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "mintBatch",
        params
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"withdraw">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "withdraw",
        params
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"getNFTUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getNFTUri",
        params
      );
    },
    getMintPrice: async (
      params: NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionSequentialWithRoyaltyTypes.SignExecuteMethodResult<"getMintPrice">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequentialWithRoyalty,
        this,
        "getMintPrice",
        params
      );
    },
  };

  async multicall<
    Calls extends NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<
    NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MultiCallResults<Calls>
  >;
  async multicall<
    Callss extends NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MultiCallParams[]
  >(
    callss: Narrow<Callss>
  ): Promise<
    NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MulticallReturnType<Callss>
  >;
  async multicall<
    Callss extends
      | NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MultiCallParams
      | NFTPublicSaleCollectionSequentialWithRoyaltyTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      NFTPublicSaleCollectionSequentialWithRoyalty,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
