/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NFTPreDesignedCollectionContractJson } from "../nft/NFTPreDesignedCollection.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace NFTPreDesignedCollectionTypes {
  export type Fields = {
    enumerableNftTemplateId: HexString;
    collectionUri: HexString;
    tokenBaseUri: HexString;
    collectionOwner: Address;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    mint: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getTokenUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  NFTPreDesignedCollectionInstance,
  NFTPreDesignedCollectionTypes.Fields
> {
  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt(0),
      NFTNotFound: BigInt(1),
      TokenOwnerAllowedOnly: BigInt(2),
    },
  };

  at(address: string): NFTPreDesignedCollectionInstance {
    return new NFTPreDesignedCollectionInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParams<NFTPreDesignedCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: Omit<
        TestContractParams<NFTPreDesignedCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "totalSupply", params);
    },
    nftByIndex: async (
      params: TestContractParams<
        NFTPreDesignedCollectionTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "nftByIndex", params);
    },
    mint: async (
      params: Omit<
        TestContractParams<NFTPreDesignedCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "mint", params);
    },
    getTokenUri: async (
      params: TestContractParams<
        NFTPreDesignedCollectionTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenUri", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NFTPreDesignedCollection = new Factory(
  Contract.fromJson(
    NFTPreDesignedCollectionContractJson,
    "",
    "f64ed2c6d97080d127f038b84ee66217ab0f9e8b2208e0ea7bb5eb6a853dea49"
  )
);

// Use this class to interact with the blockchain
export class NFTPreDesignedCollectionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPreDesignedCollectionTypes.State> {
    return fetchContractState(NFTPreDesignedCollection, this);
  }

  methods = {
    getCollectionUri: async (
      params?: NFTPreDesignedCollectionTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPreDesignedCollectionTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPreDesignedCollection,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPreDesignedCollectionTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPreDesignedCollectionTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPreDesignedCollection,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPreDesignedCollectionTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPreDesignedCollectionTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPreDesignedCollection,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params?: NFTPreDesignedCollectionTypes.CallMethodParams<"mint">
    ): Promise<NFTPreDesignedCollectionTypes.CallMethodResult<"mint">> => {
      return callMethod(
        NFTPreDesignedCollection,
        this,
        "mint",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTokenUri: async (
      params: NFTPreDesignedCollectionTypes.CallMethodParams<"getTokenUri">
    ): Promise<
      NFTPreDesignedCollectionTypes.CallMethodResult<"getTokenUri">
    > => {
      return callMethod(
        NFTPreDesignedCollection,
        this,
        "getTokenUri",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends NFTPreDesignedCollectionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<NFTPreDesignedCollectionTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      NFTPreDesignedCollection,
      this,
      calls,
      getContractByCodeHash
    )) as NFTPreDesignedCollectionTypes.MultiCallResults<Calls>;
  }
}
