/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NFTPublicSaleCollectionRandomContractJson } from "../nft/NFTPublicSaleCollectionRandom.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace NFTPublicSaleCollectionRandomTypes {
  export type Fields = {
    enumerableNftTemplateId: HexString;
    collectionUri: HexString;
    collectionOwner: Address;
    tokenBaseUri: HexString;
    maxSupply: bigint;
    mintPrice: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    mint: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTokenUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getCollectionOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getMaxSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  NFTPublicSaleCollectionRandomInstance,
  NFTPublicSaleCollectionRandomTypes.Fields
> {
  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt(0),
      NFTNotFound: BigInt(1),
      TokenOwnerAllowedOnly: BigInt(2),
    },
  };

  at(address: string): NFTPublicSaleCollectionRandomInstance {
    return new NFTPublicSaleCollectionRandomInstance(address);
  }

  tests = {
    mint: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "mint", params);
    },
    nftByIndex: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "nftByIndex", params);
    },
    getCollectionUri: async (
      params: Omit<
        TestContractParams<NFTPublicSaleCollectionRandomTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: Omit<
        TestContractParams<NFTPublicSaleCollectionRandomTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "totalSupply", params);
    },
    getTokenUri: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenUri", params);
    },
    getCollectionOwner: async (
      params: Omit<
        TestContractParams<NFTPublicSaleCollectionRandomTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getCollectionOwner", params);
    },
    getMaxSupply: async (
      params: Omit<
        TestContractParams<NFTPublicSaleCollectionRandomTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getMaxSupply", params);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParams<NFTPublicSaleCollectionRandomTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getMintPrice", params);
    },
    withdraw: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NFTPublicSaleCollectionRandom = new Factory(
  Contract.fromJson(
    NFTPublicSaleCollectionRandomContractJson,
    "",
    "3d1df3ef100afd8333c395380ef5495148d33e7edafa6f73fff1a6dd572e6fe4"
  )
);

// Use this class to interact with the blockchain
export class NFTPublicSaleCollectionRandomInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPublicSaleCollectionRandomTypes.State> {
    return fetchContractState(NFTPublicSaleCollectionRandom, this);
  }

  methods = {
    mint: async (
      params: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"mint">
    ): Promise<NFTPublicSaleCollectionRandomTypes.CallMethodResult<"mint">> => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    getCollectionUri: async (
      params?: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTokenUri: async (
      params: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"getTokenUri">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"getTokenUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "getTokenUri",
        params,
        getContractByCodeHash
      );
    },
    getCollectionOwner: async (
      params?: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"getCollectionOwner">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"getCollectionOwner">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "getCollectionOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMaxSupply: async (
      params?: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"getMaxSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"getMaxSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "getMaxSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: NFTPublicSaleCollectionRandomTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionRandomTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandom,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<
    Calls extends NFTPublicSaleCollectionRandomTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<NFTPublicSaleCollectionRandomTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      NFTPublicSaleCollectionRandom,
      this,
      calls,
      getContractByCodeHash
    )) as NFTPublicSaleCollectionRandomTypes.MultiCallResults<Calls>;
  }
}
