/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NFTPublicSaleCollectionRandomWithRoyaltyContractJson } from "../nft/publicsale/random/NFTPublicSaleCollectionRandomWithRoyalty.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace NFTPublicSaleCollectionRandomWithRoyaltyTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    collectionOwner: Address;
    nftBaseUri: HexString;
    maxSupply: bigint;
    mintPrice: bigint;
    royaltyRate: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{ minter: Address; index: bigint }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    royaltyAmount: {
      params: CallContractParams<{ tokenId: HexString; salePrice: bigint }>;
      result: CallContractResult<bigint>;
    };
    mint: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getCollectionOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getMaxSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getNFTUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  NFTPublicSaleCollectionRandomWithRoyaltyInstance,
  NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields;
  }

  eventIndex = { Mint: 0 };
  consts = {
    PublicSaleErrorCodes: { IncorrectTokenIndex: BigInt(0) },
    ErrorCodes: {
      IncorrectTokenIndex: BigInt(2),
      NFTNotFound: BigInt(0),
      CollectionOwnerAllowedOnly: BigInt(1),
    },
  };

  at(address: string): NFTPublicSaleCollectionRandomWithRoyaltyInstance {
    return new NFTPublicSaleCollectionRandomWithRoyaltyInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParams<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: Omit<
        TestContractParams<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "totalSupply", params);
    },
    nftByIndex: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "nftByIndex", params);
    },
    royaltyAmount: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { tokenId: HexString; salePrice: bigint }
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "royaltyAmount", params);
    },
    payRoyalty: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { payer: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "payRoyalty", params);
    },
    withdrawRoyalty: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdrawRoyalty", params);
    },
    mint: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "mint", params);
    },
    getCollectionOwner: async (
      params: Omit<
        TestContractParams<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getCollectionOwner", params);
    },
    getMaxSupply: async (
      params: Omit<
        TestContractParams<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getMaxSupply", params);
    },
    withdraw: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    getNFTUri: async (
      params: TestContractParams<
        NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getNFTUri", params);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParams<
          NFTPublicSaleCollectionRandomWithRoyaltyTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getMintPrice", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NFTPublicSaleCollectionRandomWithRoyalty = new Factory(
  Contract.fromJson(
    NFTPublicSaleCollectionRandomWithRoyaltyContractJson,
    "",
    "a5a8b32d5931441ac0641b7dc1f9fd0aef348d8845a6f077e01f5ddba917a312"
  )
);

// Use this class to interact with the blockchain
export class NFTPublicSaleCollectionRandomWithRoyaltyInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPublicSaleCollectionRandomWithRoyaltyTypes.State> {
    return fetchContractState(NFTPublicSaleCollectionRandomWithRoyalty, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<NFTPublicSaleCollectionRandomWithRoyaltyTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTPublicSaleCollectionRandomWithRoyalty.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  methods = {
    getCollectionUri: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    royaltyAmount: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"royaltyAmount">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"royaltyAmount">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "royaltyAmount",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"mint">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    getCollectionOwner: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getCollectionOwner">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getCollectionOwner">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getCollectionOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMaxSupply: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getMaxSupply">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getMaxSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMaxSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getNFTUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getNFTUri",
        params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionRandomWithRoyaltyTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        NFTPublicSaleCollectionRandomWithRoyalty,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<
    Calls extends NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<
    NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallResults<Calls>
  > {
    return (await multicallMethods(
      NFTPublicSaleCollectionRandomWithRoyalty,
      this,
      calls,
      getContractByCodeHash
    )) as NFTPublicSaleCollectionRandomWithRoyaltyTypes.MultiCallResults<Calls>;
  }
}
