/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as NFTPublicSaleCollectionSequentialContractJson } from "../nft/publicsale/sequential/NFTPublicSaleCollectionSequential.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace NFTPublicSaleCollectionSequentialTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    nftBaseUri: HexString;
    collectionOwner: Address;
    maxSupply: bigint;
    mintPrice: bigint;
    maxBatchMintSize: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    minter: Address;
    fromIndex: bigint;
    mintSize: bigint;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    mint_: {
      params: CallContractParams<{ minter: Address; index: bigint }>;
      result: CallContractResult<HexString>;
    };
    mint: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    mintBatch: {
      params: CallContractParams<{ size: bigint }>;
      result: CallContractResult<HexString>;
    };
    withdraw: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNFTUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint_: {
      params: SignExecuteContractMethodParams<{
        minter: Address;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    mintBatch: {
      params: SignExecuteContractMethodParams<{ size: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNFTUri: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getMintPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  NFTPublicSaleCollectionSequentialInstance,
  NFTPublicSaleCollectionSequentialTypes.Fields
> {
  encodeFields(fields: NFTPublicSaleCollectionSequentialTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Mint: 0 };
  consts = {
    PublicSaleErrorCodes: { IncorrectTokenIndex: BigInt("0") },
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("2"),
      InvalidMintBatchSize: BigInt("3"),
      InsufficientNumOfUnminted: BigInt("4"),
      NFTNotFound: BigInt("0"),
      CollectionOwnerAllowedOnly: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): NFTPublicSaleCollectionSequentialInstance {
    return new NFTPublicSaleCollectionSequentialInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    mint_: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { minter: Address; index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint_", params, getContractByCodeHash);
    },
    mint: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    mintBatch: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { size: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mintBatch", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    getNFTUri: async (
      params: TestContractParamsWithoutMaps<
        NFTPublicSaleCollectionSequentialTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getNFTUri", params, getContractByCodeHash);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          NFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMintPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: NFTPublicSaleCollectionSequentialTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const NFTPublicSaleCollectionSequential = new Factory(
  Contract.fromJson(
    NFTPublicSaleCollectionSequentialContractJson,
    "",
    "0465ef0b67a5ba3f4a06a375a64d19137b968b8e59618a8bb59b6792e10e6fd9",
    []
  )
);
registerContract(NFTPublicSaleCollectionSequential);

// Use this class to interact with the blockchain
export class NFTPublicSaleCollectionSequentialInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTPublicSaleCollectionSequentialTypes.State> {
    return fetchContractState(NFTPublicSaleCollectionSequential, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<NFTPublicSaleCollectionSequentialTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTPublicSaleCollectionSequential.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"validateNFT">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    mint_: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mint_">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mint_">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mint_",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params?: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mint">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mint",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    mintBatch: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mintBatch">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mintBatch">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mintBatch",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"withdraw">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getNFTUri">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getNFTUri",
        params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: NFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "validateNFT",
        params
      );
    },
    mint_: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mint_">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mint_">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mint_",
        params
      );
    },
    mint: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mint">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mint">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mint",
        params
      );
    },
    mintBatch: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mintBatch">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mintBatch">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "mintBatch",
        params
      );
    },
    withdraw: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"withdraw">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "withdraw",
        params
      );
    },
    getNFTUri: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getNFTUri">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getNFTUri">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getNFTUri",
        params
      );
    },
    getMintPrice: async (
      params: NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getMintPrice">
    ): Promise<
      NFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getMintPrice">
    > => {
      return signExecuteMethod(
        NFTPublicSaleCollectionSequential,
        this,
        "getMintPrice",
        params
      );
    },
  };

  async multicall<
    Calls extends NFTPublicSaleCollectionSequentialTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<NFTPublicSaleCollectionSequentialTypes.MultiCallResults<Calls>>;
  async multicall<
    Callss extends NFTPublicSaleCollectionSequentialTypes.MultiCallParams[]
  >(
    callss: Narrow<Callss>
  ): Promise<
    NFTPublicSaleCollectionSequentialTypes.MulticallReturnType<Callss>
  >;
  async multicall<
    Callss extends
      | NFTPublicSaleCollectionSequentialTypes.MultiCallParams
      | NFTPublicSaleCollectionSequentialTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      NFTPublicSaleCollectionSequential,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
