/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NonEnumerableNFTContractJson } from "../nft/non-enumerable-nft.ral.json";

// Custom types for the contract
export namespace NonEnumerableNFTTypes {
  export type Fields = {
    collectionId: HexString;
    uri: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  NonEnumerableNFTInstance,
  NonEnumerableNFTTypes.Fields
> {
  at(address: string): NonEnumerableNFTInstance {
    return new NonEnumerableNFTInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParams<NonEnumerableNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenUri", params);
    },
    getCollectionId: async (
      params: Omit<
        TestContractParams<NonEnumerableNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getCollectionId", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NonEnumerableNFT = new Factory(
  Contract.fromJson(
    NonEnumerableNFTContractJson,
    "",
    "657b46b2236b78c955660db6731d43b42dd8204bb6220181de3c5f8678d90da0"
  )
);

// Use this class to interact with the blockchain
export class NonEnumerableNFTInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NonEnumerableNFTTypes.State> {
    return fetchContractState(NonEnumerableNFT, this);
  }

  methods = {
    getTokenUri: async (
      params?: NonEnumerableNFTTypes.CallMethodParams<"getTokenUri">
    ): Promise<NonEnumerableNFTTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        NonEnumerableNFT,
        this,
        "getTokenUri",
        params === undefined ? {} : params
      );
    },
    getCollectionId: async (
      params?: NonEnumerableNFTTypes.CallMethodParams<"getCollectionId">
    ): Promise<NonEnumerableNFTTypes.CallMethodResult<"getCollectionId">> => {
      return callMethod(
        NonEnumerableNFT,
        this,
        "getCollectionId",
        params === undefined ? {} : params
      );
    },
  };

  async multicall<Calls extends NonEnumerableNFTTypes.MultiCallParams>(
    calls: Calls
  ): Promise<NonEnumerableNFTTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      NonEnumerableNFT,
      this,
      calls
    )) as NonEnumerableNFTTypes.MultiCallResults<Calls>;
  }
}
