name: Unit-Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: start ALPH docker image
        working-directory: ./test/docker
        run: docker-compose up -d
      - name: Run tests
        run: |
          npm ci
          npm run test:contracts
